name: login_register_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  cloud_firestore: ^4.13.2
  fluttertoast: ^8.2.4
  firebase_database: ^10.1.0
  path_provider: ^2.0.14
  webview_flutter: ^4.0.7
  search_page: ^2.3.0
  flutter_inappwebview: ^5.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
